// Coin
export const GET_COIN_SUCCESS = 'GET_COIN_SUCCESS';
export const GET_COIN_FAILED = 'GET_COIN_FAILED';
export const GET_COIN_SOMETHING_WRONG = 'GET_COIN_SOMETHING_WRONG';
export const GET_COIN_FINISH = 'GET_COIN_FINISH';
export const GET_COIN_PAGINATION = 'GET_COIN_PAGINATION';
export const GET_COIN_ID = 'GET_COIN_ID';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';